-- =============================================================================
-- SEED External API dari snapshot: okeh8644
-- Generate: php docs/scripts/build_external_api_snapshot_sql.php okeh8644
-- Jalankan SETELAH import pegasus_live_fase2_export.sql
-- =============================================================================

-- Prasyarat DDL (jalankan dulu kalau tabel belum ada):
--   database/sql/2026_07_28_220000_create_external_applications_table.sql
--   database/sql/2026_08_17_090000_create_external_api_endpoints_table.sql

SET NAMES utf8mb4;

-- --- DATA external_applications (1 baris) ---
INSERT INTO `external_applications` (`external_application_id`, `application_code`, `application_name`, `company`, `contact_name`, `contact_email`, `description`, `application_status`, `created_by`, `updated_by`, `status`, `created_at`, `updated_at`) VALUES (1, 'PMO', 'PMO', 'Pegasus (Internal PMO)', NULL, NULL, NULL, 'active', 13, NULL, 1, '2026-08-18 20:15:34', '2026-08-18 20:15:34') ON DUPLICATE KEY UPDATE `application_code`=VALUES(`application_code`), `application_name`=VALUES(`application_name`), `company`=VALUES(`company`), `contact_name`=VALUES(`contact_name`), `contact_email`=VALUES(`contact_email`), `description`=VALUES(`description`), `application_status`=VALUES(`application_status`), `created_by`=VALUES(`created_by`), `updated_by`=VALUES(`updated_by`), `status`=VALUES(`status`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);

-- --- DATA external_api_keys (1 baris) ---
INSERT INTO `external_api_keys` (`external_api_key_id`, `external_application_id`, `key_name`, `environment`, `key_prefix`, `key_hash`, `key_last_four`, `key_status`, `expires_at`, `last_used_at`, `revoked_at`, `revoked_by`, `created_by`, `status`, `created_at`, `updated_at`) VALUES (1, 1, 'PMO1', 'development', 'ext_dev_Y3ZcKYgM3Ffx', 'cf86c5d41df1e262074667c82d175681680110ffeaf9a161580579ed724378ac', '4dQ7', 'active', NULL, NULL, NULL, NULL, 13, 1, '2026-08-18 20:16:01', '2026-08-18 20:16:01') ON DUPLICATE KEY UPDATE `external_application_id`=VALUES(`external_application_id`), `key_name`=VALUES(`key_name`), `environment`=VALUES(`environment`), `key_prefix`=VALUES(`key_prefix`), `key_hash`=VALUES(`key_hash`), `key_last_four`=VALUES(`key_last_four`), `key_status`=VALUES(`key_status`), `expires_at`=VALUES(`expires_at`), `last_used_at`=VALUES(`last_used_at`), `revoked_at`=VALUES(`revoked_at`), `revoked_by`=VALUES(`revoked_by`), `created_by`=VALUES(`created_by`), `status`=VALUES(`status`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);

-- --- DATA external_api_endpoints (33 baris) ---
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (1, 'armada', 0, 0, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (2, 'armada-create', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (3, 'armada-delete', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (4, 'armada-update', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (5, 'master-cash-categories', 0, 0, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (6, 'master-sales', 0, 0, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (7, 'master-sales-connect', 0, 0, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (8, 'master-sales-create', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (9, 'master-sales-delete', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (10, 'master-sales-update', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (11, 'master-units', 0, 0, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (12, 'master-units-connect', 0, 0, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (13, 'master-units-create', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (14, 'master-units-delete', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (15, 'master-units-update', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (16, 'master-warehouse-types', 0, 0, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (17, 'master-warehouses', 0, 0, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (18, 'master-warehouses-create', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (19, 'master-warehouses-delete', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (20, 'master-warehouses-update', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (21, 'pembayaran-kas-buat', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (22, 'pembayaran-kas-detail', 0, 0, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (23, 'produk', 0, 0, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (24, 'produk-connect', 0, 0, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (25, 'produk-create', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (26, 'produk-delete', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (27, 'produk-update', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (28, 'shipment-cancel', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (29, 'shipment-change-status', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (30, 'shipment-scheduled', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (31, 'shipment-shipped', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (32, 'shipment-show', 0, 0, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);
INSERT INTO `external_api_endpoints` (`external_api_endpoint_id`, `endpoint_key`, `is_active`, `is_public_docs_show`, `created_at`, `updated_at`) VALUES (33, 'stok-cek', 1, 1, '2026-08-18 19:32:06', '2026-08-18 19:32:06') ON DUPLICATE KEY UPDATE `endpoint_key`=VALUES(`endpoint_key`), `is_active`=VALUES(`is_active`), `is_public_docs_show`=VALUES(`is_public_docs_show`), `created_at`=VALUES(`created_at`), `updated_at`=VALUES(`updated_at`);

SELECT 'seed_external_api_from_snapshot OK' AS result;
SELECT COUNT(*) AS external_applications FROM external_applications;
SELECT COUNT(*) AS external_api_keys FROM external_api_keys;
SELECT COUNT(*) AS external_api_endpoints FROM external_api_endpoints;
