<?php

/*
|--------------------------------------------------------------------------
| AI Vocabulary (front-end language layer)
|--------------------------------------------------------------------------
| The AI assistant must never speak in storage terms. This file is the only
| translation layer between raw storage keys and the wording users see in
| the app:
|
|   - "modules"  : business module name => where its data lives, which code
|                  fields identify a document, its date and amount field,
|                  and its line-item child. Tools accept module names, so
|                  the model can ask for "pengiriman" instead of a raw name.
|   - "labels"   : raw key => UI label. Tool output is re-keyed with these
|                  labels, so raw keys never reach the model at all.
|   - "status"   : numeric status => UI badge text, per module.
|   - "values"   : other coded fields (payment state, cash direction, ...).
|   - "lookups"  : reference key => where to read its human name, so rows
|                  come back as "Customer: PT Maju" instead of an id.
|
| Anything not listed still works: Vocabulary::label() humanises unknown
| keys and drops them from lookups.
*/

return [

    /*
    | Business module => storage mapping.
    | aliases: extra wording the model (or user) may use for the same module.
    | codes  : document code fields, searched by find_document in this order.
    | detail : line items child table + foreign key.
    */
    'modules' => [
        'pengiriman' => [
            'table' => 'sales_orders',
            'label' => 'Pengiriman (Sales Order)',
            'aliases' => ['sales order', 'so', 'penjualan', 'invoice penjualan', 'order penjualan'],
            'codes' => ['so_invoice_no', 'so_number', 'so_ref_number'],
            'date' => 'so_date',
            'amount' => 'so_total',
            'detail' => ['table' => 'sales_order_details', 'fk' => 'so_id'],
        ],
        'surat jalan' => [
            'table' => 'sales_delivery_orders',
            'label' => 'Surat Jalan Pengiriman',
            'aliases' => ['delivery order', 'sj', 'sdo'],
            'codes' => ['sdo_number'],
            'date' => 'sdo_date',
            'detail' => ['table' => 'sales_delivery_orders_details', 'fk' => 'sdo_id'],
        ],
        'invoice penjualan' => [
            'table' => 'sales_order_detail_invoices',
            'label' => 'Invoice Penjualan',
            'aliases' => ['tagihan penjualan'],
            'codes' => ['soi_code'],
            'date' => 'soi_date',
            'amount' => 'soi_total',
        ],
        'pembelian' => [
            'table' => 'purchase_orders',
            'label' => 'Pembelian (Purchase Order)',
            'aliases' => ['purchase order', 'po', 'pesanan pembelian'],
            'codes' => ['po_number'],
            'date' => 'po_date',
            'amount' => 'po_total',
            'detail' => ['table' => 'purchase_orders_details', 'fk' => 'po_id'],
        ],
        'tanda terima' => [
            'table' => 'purchase_order_tts',
            'label' => 'Tanda Terima Pembelian',
            'aliases' => ['tt', 'tanda terima pembelian'],
            'codes' => ['tt_kode'],
            'date' => 'tt_date',
            'amount' => 'tt_total',
        ],
        'invoice pembelian' => [
            'table' => 'purchase_order_detail_invoices',
            'label' => 'Invoice Pembelian',
            'aliases' => ['tagihan pembelian'],
            'codes' => ['poi_code'],
            'date' => 'poi_date',
            'amount' => 'poi_total',
        ],
        'penerimaan pembelian' => [
            'table' => 'purchase_delivery_orders',
            'label' => 'Penerimaan Barang Pembelian (riwayat)',
            'aliases' => ['pengiriman pembelian', 'pdo'],
            'codes' => ['pdo_number'],
            'date' => 'pdo_date',
            'detail' => ['table' => 'purchase_delivery_orders_details', 'fk' => 'pdo_id'],
        ],
        'produksi' => [
            'table' => 'productions',
            'label' => 'Produksi',
            'aliases' => ['production'],
            'codes' => ['production_code'],
            'date' => 'production_date',
            'detail' => ['table' => 'production_details', 'fk' => 'production_id'],
        ],
        'resep' => [
            'table' => 'boms',
            'label' => 'Resep (BOM)',
            'aliases' => ['bom', 'formula'],
            'date' => 'created_at',
            'detail' => ['table' => 'bom_details', 'fk' => 'bom_id'],
        ],
        'opname produk' => [
            'table' => 'stock_opnames',
            'label' => 'Stok Opname Produk',
            'aliases' => ['stok opname produk', 'opname'],
            'codes' => ['sto_code'],
            'date' => 'sto_date',
            'detail' => ['table' => 'stock_opname_lines', 'fk' => 'sto_id'],
        ],
        'opname bahan' => [
            'table' => 'stock_opname_bahans',
            'label' => 'Stok Opname Bahan Mentah',
            'aliases' => ['stok opname bahan'],
            'codes' => ['stob_code'],
            'date' => 'stob_date',
            'detail' => ['table' => 'stock_opname_bahan_lines', 'fk' => 'stob_id'],
        ],
        'produk bermasalah' => [
            'table' => 'product_issues',
            'label' => 'Produk Bermasalah',
            'aliases' => ['product issue', 'barang rusak'],
            // Own document code only (PI…). Do NOT use ref_num here — that is a
            // pointer to another document and must never steal ST/PO/SO lookups.
            'codes' => ['pi_code'],
            'date' => 'pi_date',
            'detail' => ['table' => 'product_issues_details', 'fk' => 'pi_id'],
        ],
        'retur ke pemasok' => [
            'table' => 'return_supplies',
            'label' => 'Retur ke Pemasok',
            'aliases' => ['retur supplier', 'return supplies'],
            'date' => 'rs_date',
            'amount' => 'rs_total',
            'detail' => ['table' => 'return_supplies_detail', 'fk' => 'rs_id'],
        ],
        'retur produk dari customer' => [
            'table' => 'customer_product_returns',
            'label' => 'Retur Produk dari Customer',
            'aliases' => ['retur produk customer'],
            'codes' => ['return_number', 'ref_number'],
            'date' => 'return_date',
            'detail' => ['table' => 'customer_product_return_details', 'fk' => 'return_id'],
        ],
        'retur bahan dari customer' => [
            'table' => 'customer_supply_returns',
            'label' => 'Retur Bahan dari Customer',
            'aliases' => ['retur bahan customer'],
            'codes' => ['return_number', 'ref_number'],
            'date' => 'return_date',
            'detail' => ['table' => 'customer_supply_return_details', 'fk' => 'return_id'],
        ],
        'transfer stok' => [
            'table' => 'stock_transfers',
            'label' => 'Transfer Stok antar Gudang',
            'aliases' => ['mutasi gudang', 'stock transfer', 'stok transfer', 'transfer antar gudang', 'st'],
            'codes' => ['transfer_code'],
            'date' => 'transfer_date',
            'detail' => ['table' => 'stock_transfer_details', 'fk' => 'st_id'],
        ],
        'stok produk' => [
            'table' => 'product_stocks',
            'label' => 'Stok Produk',
            'aliases' => ['stock produk', 'sisa stok produk'],
            'date' => 'updated_at',
            'amount' => 'ps_stock',
        ],
        'stok bahan' => [
            'table' => 'supplies_stocks',
            'label' => 'Stok Bahan Mentah',
            'aliases' => ['stock bahan', 'sisa stok bahan'],
            'date' => 'updated_at',
            'amount' => 'ss_stock',
        ],
        'riwayat stok' => [
            'table' => 'log_stocks',
            'label' => 'Riwayat Pergerakan Stok',
            'aliases' => ['mutasi stok', 'log stok', 'kartu stok'],
            'codes' => ['log_kode'],
            'date' => 'log_date',
            'amount' => 'log_jumlah',
        ],
        'pengelolaan bahan' => [
            'table' => 'manage_stocks',
            'label' => 'Pengelolaan Stok Manual',
            'aliases' => ['manage stock', 'penyesuaian stok'],
            'date' => 'created_at',
            'amount' => 'ms_stock',
        ],
        'kas umum' => [
            'table' => 'cashes',
            'label' => 'Kas (Kas Besar)',
            'aliases' => ['kas besar', 'kas'],
            'date' => 'cash_date',
            'amount' => 'cash_nominal',
        ],
        'kas admin' => [
            'table' => 'cash_admins',
            'label' => 'Kas Operasional Admin',
            'aliases' => ['operasional admin'],
            'date' => 'ca_date',
            'amount' => 'ca_nominal',
            'detail' => ['table' => 'cash_admin_details', 'fk' => 'ca_id'],
        ],
        'kas gudang' => [
            'table' => 'cash_gudangs',
            'label' => 'Kas Operasional Gudang',
            'aliases' => ['operasional gudang'],
            'date' => 'cg_date',
            'amount' => 'cg_nominal',
            'detail' => ['table' => 'cash_gudang_details', 'fk' => 'cg_id'],
        ],
        'kas armada' => [
            'table' => 'cash_armadas',
            'label' => 'Kas Operasional Armada',
            'aliases' => ['operasional armada', 'armada'],
            'date' => 'cr_date',
            'amount' => 'cr_nominal',
            'detail' => ['table' => 'cash_armada_details', 'fk' => 'cr_id'],
        ],
        'kas sales' => [
            'table' => 'cash_sales',
            'label' => 'Kas Operasional Sales',
            'aliases' => ['operasional sales'],
            'date' => 'cs_date',
            'amount' => 'cs_nominal',
            'detail' => ['table' => 'cash_sales_details', 'fk' => 'cs_id'],
        ],
        'petty cash' => [
            'table' => 'petty_cashes',
            'label' => 'Petty Cash',
            'aliases' => ['kas kecil'],
            'date' => 'pc_date',
        ],
        'kategori kas' => [
            'table' => 'cash_categories',
            'label' => 'Kategori Kas',
            'date' => 'created_at',
        ],
        'bank' => [
            'table' => 'banks',
            'label' => 'Akun Bank',
            'aliases' => ['rekening'],
            'date' => 'created_at',
        ],
        'produk' => [
            'table' => 'products',
            'label' => 'Produk',
            'aliases' => ['daftar produk', 'barang'],
            'date' => 'created_at',
        ],
        'varian produk' => [
            'table' => 'product_variants',
            'label' => 'Varian Produk',
            'aliases' => ['varian', 'sku produk'],
            'codes' => ['product_variant_sku', 'product_variant_barcode'],
            'date' => 'created_at',
        ],
        'konversi satuan produk' => [
            'table' => 'product_relations',
            'label' => 'Konversi Satuan Produk',
            'date' => 'created_at',
        ],
        'bahan' => [
            'table' => 'supplies',
            'label' => 'Bahan Mentah',
            'aliases' => ['bahan mentah', 'daftar bahan'],
            'date' => 'created_at',
        ],
        'varian bahan' => [
            'table' => 'supplies_variants',
            'label' => 'Varian Bahan Mentah',
            'codes' => ['supplies_variant_sku', 'supplies_variant_barcode'],
            'date' => 'created_at',
        ],
        'konversi satuan bahan' => [
            'table' => 'supplies_relations',
            'label' => 'Konversi Satuan Bahan',
            'date' => 'created_at',
        ],
        'kategori' => ['table' => 'categories', 'label' => 'Kategori', 'date' => 'created_at'],
        'satuan' => ['table' => 'units', 'label' => 'Satuan', 'date' => 'created_at'],
        'variasi' => ['table' => 'variants', 'label' => 'Variasi', 'date' => 'created_at'],
        'customer' => [
            'table' => 'customers',
            'label' => 'Customer',
            'aliases' => ['pelanggan', 'klien'],
            'codes' => ['customer_code'],
            'date' => 'created_at',
        ],
        'pemasok' => [
            'table' => 'suppliers',
            'label' => 'Pemasok',
            'aliases' => ['supplier', 'vendor'],
            'codes' => ['supplier_code'],
            'date' => 'created_at',
        ],
        'pengguna' => [
            'table' => 'staffs',
            'label' => 'Pengguna',
            'aliases' => ['staff', 'karyawan', 'user'],
            'codes' => ['staff_code', 'staff_username'],
            'date' => 'created_at',
        ],
        'peran' => ['table' => 'roles', 'label' => 'Peran', 'aliases' => ['role', 'hak akses'], 'date' => 'created_at'],
        'gudang' => ['table' => 'warehouses', 'label' => 'Gudang', 'aliases' => ['cabang', 'warehouse'], 'date' => 'created_at'],
        'tipe gudang' => ['table' => 'warehouse_types', 'label' => 'Tipe Gudang', 'date' => 'created_at'],
        'penempatan pengguna' => ['table' => 'staff_warehouses', 'label' => 'Penempatan Pengguna di Gudang', 'date' => 'created_at'],
        'area' => ['table' => 'areas', 'label' => 'Area', 'aliases' => ['wilayah'], 'date' => 'created_at'],
        'aktivitas' => [
            'table' => 'dashboard_change_logs',
            'label' => 'Aktivitas Pengguna',
            'aliases' => ['log aktivitas', 'perubahan data'],
            'date' => 'created_at',
        ],
    ],

    /*
    | Raw key => UI label. Used to re-key every row before it leaves a tool.
    */
    'labels' => [
        // shared
        'status' => 'Status',
        'created_at' => 'Dibuat',
        'updated_at' => 'Diperbarui',
        'created_by' => 'Dibuat Oleh',
        'updated_by' => 'Diubah Oleh',
        'acc_by' => 'Disetujui Oleh',
        'qc_staff_id' => 'Petugas QC',
        'qc_approved_by' => 'Disetujui QC',
        'qc_approved_at' => 'Waktu Setuju QC',
        'ops_approved_by' => 'Disetujui Operasional',
        'ops_approved_at' => 'Waktu Setuju Operasional',
        'staff_id' => 'Pengguna',
        'person_id' => 'Pengguna',
        'unit_id' => 'Satuan',
        'warehouse_id' => 'Gudang',
        'notes' => 'Catatan',
        'note' => 'Catatan',
        'qty' => 'Qty',
        'qty_received' => 'Qty Diterima',
        'bank_id' => 'Bank',
        'cc_id' => 'Kategori Kas',
        'category_id' => 'Kategori',
        'customer_id' => 'Customer',
        'supplier_id' => 'Pemasok',
        'product_id' => 'Produk',
        'product_variant_id' => 'Varian Produk',
        'supplies_id' => 'Bahan',
        'supplies_variant_id' => 'Varian Bahan',
        'role_id' => 'Peran',
        'area_id' => 'Area',
        'is_draft' => 'Draft',
        'is_old_version' => 'Versi Lama',
        'resolved_by_system' => 'Diselesaikan Sistem',

        // pengiriman / sales order
        'so_id' => 'Ref Pengiriman',
        'so_number' => 'No. SO',
        'so_invoice_no' => 'No. Invoice',
        'so_ref_number' => 'No. Referensi',
        'so_date' => 'Tanggal',
        'so_customer' => 'Customer',
        'so_total' => 'Total',
        'so_discount' => 'Diskon',
        'so_ppn' => 'PPN',
        'so_cost' => 'Biaya',
        'so_paid' => 'Dibayar',
        'so_difference' => 'Selisih Bayar',
        'so_cashier' => 'Kasir',
        'cancel_reason' => 'Alasan Batal',
        'retail_warehouse_id' => 'Gudang Retail',
        'sod_nama' => 'Produk',
        'sod_variant' => 'Varian',
        'sod_sku' => 'SKU',
        'sod_harga' => 'Harga',
        'sod_qty' => 'Qty',
        'sod_subtotal' => 'Subtotal',
        'sdo_number' => 'No. Surat Jalan',
        'sdo_receiver' => 'Penerima',
        'sdo_date' => 'Tanggal Kirim',
        'sdo_desc' => 'Keterangan',
        'sdod_sku' => 'SKU',
        'sdod_qty' => 'Qty',
        'soi_code' => 'No. Invoice',
        'soi_date' => 'Tanggal Invoice',
        'soi_due' => 'Jatuh Tempo',
        'soi_total' => 'Total Invoice',

        // pembelian
        'po_id' => 'Ref Pembelian',
        'po_number' => 'No. PO',
        'po_date' => 'Tanggal',
        'po_supplier' => 'Pemasok',
        'po_total' => 'Total',
        'po_discount' => 'Diskon',
        'jenis_discount' => 'Jenis Diskon',
        'po_ppn' => 'PPN',
        'po_cost' => 'Biaya',
        'po_desc' => 'Keterangan',
        'pembayaran' => 'Status Pembayaran',
        'tt_id' => 'Ref Tanda Terima',
        'pod_nama' => 'Bahan',
        'pod_variant' => 'Varian',
        'pod_sku' => 'SKU',
        'pod_harga' => 'Harga',
        'pod_qty' => 'Qty',
        'pod_subtotal' => 'Subtotal',
        'tt_kode' => 'No. Tanda Terima',
        'tt_date' => 'Tanggal',
        'tt_due' => 'Jatuh Tempo',
        'tt_total' => 'Total',
        'tt_desc' => 'Keterangan',
        'staff_name' => 'Petugas',
        'staffFinance_name' => 'Petugas Finance',
        'poi_code' => 'No. Invoice',
        'poi_date' => 'Tanggal Invoice',
        'poi_due' => 'Jatuh Tempo',
        'poi_total' => 'Total Invoice',
        'pdo_number' => 'No. Penerimaan',
        'pdo_receiver' => 'Penerima',
        'pdo_date' => 'Tanggal',
        'pdo_desc' => 'Keterangan',
        'pdod_sku' => 'SKU',
        'pdod_qty' => 'Qty',

        // produksi & resep
        'production_id' => 'Ref Produksi',
        'production_code' => 'No. Produksi',
        'production_date' => 'Tanggal',
        'production_desc' => 'Keterangan',
        'production_created_by' => 'Dibuat Oleh',
        'cancel_requested_by' => 'Pengaju Batal',
        'pd_qty' => 'Qty',
        'destination_warehouse_id' => 'Gudang Tujuan',
        'bom_id' => 'Resep',
        'bom_qty' => 'Qty Hasil',
        'bom_detail_qty' => 'Qty Bahan',

        // stok & opname
        'ps_stock' => 'Stok',
        'ps_safety_stock' => 'Stok Aman',
        'ps_alert_stock' => 'Batas Peringatan',
        'ps_min_order' => 'Minimum Order',
        'ss_stock' => 'Stok',
        'product_variant_name' => 'Varian Produk',
        'product_variant_sku' => 'SKU',
        'product_variant_price' => 'Harga',
        'product_variant_stock' => 'Stok Varian',
        'product_variant_barcode' => 'Barcode',
        'product_variant_alert' => 'Batas Peringatan',
        'retail_unit' => 'Satuan Retail',
        'qty_per_pallet' => 'Qty per Pallet',
        'safety_stock' => 'Stok Aman',
        'lead_time_days' => 'Lead Time (hari)',
        'product_name' => 'Produk',
        'product_kind' => 'Jenis Produk',
        'product_unit' => 'Satuan',
        'product_alert' => 'Batas Peringatan',
        'supplies_name' => 'Bahan',
        'supplies_kind' => 'Jenis Bahan',
        'supplies_desc' => 'Keterangan',
        'supplies_unit' => 'Satuan',
        'supplies_default_unit' => 'Satuan Utama',
        'supplies_min_stock' => 'Stok Minimum',
        'supplies_alert' => 'Batas Peringatan',
        'supplies_variant_name' => 'Varian Bahan',
        'supplies_variant_sku' => 'SKU',
        'supplies_variant_price' => 'Harga',
        'supplies_variant_stock' => 'Stok Varian',
        'sto_code' => 'No. Opname',
        'sto_date' => 'Tanggal',
        'sto_notes' => 'Catatan',
        'sto_staff_name' => 'Petugas',
        'sto_acc_name' => 'Disetujui Oleh',
        'sto_decided_at' => 'Waktu Keputusan',
        'sol_counted_qty' => 'Qty Fisik',
        'sol_system_qty_final' => 'Qty Sistem',
        'sol_use_system_stock' => 'Pakai Stok Sistem',
        'sol_notes' => 'Catatan',
        'sol_product_name' => 'Produk',
        'sol_variant_name' => 'Varian',
        'sol_variant_sku' => 'SKU',
        'sol_unit_name' => 'Satuan',
        'stod_system' => 'Qty Sistem',
        'stod_real' => 'Qty Fisik',
        'stod_selisih' => 'Selisih',
        'stod_notes' => 'Catatan',
        'stob_code' => 'No. Opname',
        'stob_date' => 'Tanggal',
        'stob_notes' => 'Catatan',
        'stob_staff_name' => 'Petugas',
        'stob_acc_name' => 'Disetujui Oleh',
        'stob_decided_at' => 'Waktu Keputusan',
        'sobl_counted_qty' => 'Qty Fisik',
        'sobl_system_qty_final' => 'Qty Sistem',
        'sobl_notes' => 'Catatan',
        'sobl_supplies_name' => 'Bahan',
        'sobl_unit_name' => 'Satuan',
        'stobd_system' => 'Qty Sistem',
        'stobd_real' => 'Qty Fisik',
        'stobd_selisih' => 'Selisih',
        'stobd_notes' => 'Catatan',
        'ms_type' => 'Jenis Penyesuaian',
        'ms_stock' => 'Qty',
        'ms_created_by' => 'Dibuat Oleh',
        'log_date' => 'Tanggal',
        'log_kode' => 'No. Dokumen',
        'log_type' => 'Jenis Item',
        'log_category' => 'Arah Mutasi',
        'log_item_id' => 'Item',
        'log_notes' => 'Catatan',
        'log_jumlah' => 'Jumlah',
        'log_saldo' => 'Saldo Setelah',

        // produk bermasalah & retur
        'pi_code' => 'No. Dokumen',
        'pi_date' => 'Tanggal',
        'pi_notes' => 'Catatan',
        'pi_type' => 'Jenis Masalah',
        'tipe_return' => 'Tipe Retur',
        'ref_num' => 'No. Referensi',
        'source_type' => 'Sumber',
        'pid_qty' => 'Qty',
        'rs_date' => 'Tanggal',
        'rs_notes' => 'Catatan',
        'rs_total' => 'Total',
        'rsd_qty' => 'Qty',
        'rsd_price' => 'Harga',
        'return_number' => 'No. Retur',
        'return_group' => 'Grup Retur',
        'return_date' => 'Tanggal',
        'ref_number' => 'No. Referensi',

        // transfer stok
        'transfer_code' => 'No. Transfer',
        'transfer_date' => 'Tanggal',
        'sender_id' => 'Pengirim',
        'receiver_id' => 'Penerima',
        'from_warehouse_id' => 'Gudang Asal',
        'to_warehouse_id' => 'Gudang Tujuan',
        'accept_note' => 'Catatan Penerimaan',
        'disposition' => 'Disposisi',
        'received_unit_id' => 'Satuan Diterima',

        // kas
        'cash_date' => 'Tanggal',
        'cash_type' => 'Jenis',
        'cash_tujuan' => 'Tujuan',
        'cash_description' => 'Keterangan',
        'cash_nominal' => 'Nominal',
        'ca_date' => 'Tanggal',
        'ca_nominal' => 'Nominal',
        'ca_notes' => 'Catatan',
        'ca_type' => 'Jenis',
        'ca_aksi' => 'Aksi',
        'cad_notes' => 'Keterangan',
        'cad_nominal' => 'Nominal',
        'cg_date' => 'Tanggal',
        'cg_nominal' => 'Nominal',
        'cg_notes' => 'Catatan',
        'cg_type' => 'Jenis',
        'cg_aksi' => 'Aksi',
        'cgd_notes' => 'Keterangan',
        'cgd_nominal' => 'Nominal',
        'cr_date' => 'Tanggal',
        'cr_nominal' => 'Nominal',
        'cr_notes' => 'Catatan',
        'cr_type' => 'Jenis',
        'cr_aksi' => 'Aksi',
        'crd_notes' => 'Keterangan',
        'crd_nominal' => 'Nominal',
        'crd_type' => 'Jenis',
        'cs_date' => 'Tanggal',
        'cs_nominal' => 'Nominal',
        'cs_notes' => 'Catatan',
        'cs_type' => 'Jenis',
        'cs_aksi' => 'Aksi',
        'cs_transaction' => 'No. Transaksi',
        'csd_notes' => 'Keterangan',
        'csd_nominal' => 'Nominal',
        'csd_type' => 'Jenis',
        'pc_date' => 'Tanggal',
        'pcd_notes' => 'Keterangan',
        'pcd_nominal' => 'Nominal',
        'cc_name' => 'Kategori Kas',
        'cc_type' => 'Jenis Kategori',
        'bank_kode' => 'Bank',
        'source_cgd_id' => 'Ref Sumber Kas Gudang',

        // master data
        'category_name' => 'Kategori',
        'unit_name' => 'Satuan',
        'unit_short_name' => 'Singkatan Satuan',
        'variant_name' => 'Variasi',
        'variant_attribute' => 'Atribut Variasi',
        'customer_name' => 'Customer',
        'customer_code' => 'Kode Customer',
        'customer_email' => 'Email',
        'customer_pic' => 'PIC',
        'customer_category' => 'Kategori Customer',
        'customer_lokasi' => 'Lokasi',
        'customer_saldo' => 'Saldo',
        'customer_notes' => 'Nama Customer',
        'sales_id' => 'Sales',
        'supplier_name' => 'Pemasok',
        'supplier_code' => 'Kode Pemasok',
        'supplier_email' => 'Email',
        'supplier_pic' => 'PIC',
        'supplier_notes' => 'Catatan',
        'supplier_bank' => 'Bank',
        'supplier_branch' => 'Cabang Bank',
        'supplier_account_name' => 'Nama Rekening',
        'supplier_top' => 'Termin Pembayaran',
        'supplier_payment' => 'Metode Pembayaran',
        'staff_name' => 'Nama Pengguna',
        'staff_code' => 'Kode Pengguna',
        'staff_email' => 'Email',
        'staff_username' => 'Username',
        'staff_saldo' => 'Saldo',
        'staff_notes' => 'Catatan',
        'last_active_warehouse_id' => 'Gudang Terakhir',
        'role_name' => 'Peran',
        'warehouse_name' => 'Gudang',
        'warehouse_type_id' => 'Tipe Gudang',
        'warehouse_type_name' => 'Tipe Gudang',
        'is_main_warehouse' => 'Gudang Utama',
        'is_kepala_cabang' => 'Kepala Cabang',
        'area_code' => 'Kode Area',
        'area_name' => 'Area',
        'prov_name' => 'Provinsi',
        'city_name' => 'Kota',

        // aktivitas
        'module_key' => 'Modul',
        'module_label' => 'Modul',
        'activity_type' => 'Jenis Aktivitas',
        'reference' => 'Referensi',
        'what_changed' => 'Yang Diubah',
        'summary' => 'Ringkasan',
        'duration_seconds' => 'Durasi (detik)',
    ],

    /*
    | Numeric status => UI badge text. "default" applies to modules without
    | their own map and only covers the universal active/inactive flag; any
    | other code is shown as "belum terdaftar" so the AI never guesses its
    | meaning (Vocabulary::statusLabel()).
    |
    | "inactive_words": labels that mean the record no longer counts
    | (deleted / rejected / cancelled / inactive). search_records and
    | summarize_records leave those out unless the user asks for a status.
    */
    'status' => [
        'default' => [1 => 'Aktif', 0 => 'Nonaktif'],
        'inactive_words' => ['hapus', 'tolak', 'batal', 'nonaktif'],
        'tables' => [
            'sales_orders' => [1 => 'Menunggu', 2 => 'Disetujui', 3 => 'Ditolak/Dihapus', 0 => 'Dihapus'],
            'sales_order_details' => [1 => 'Menunggu', 2 => 'Disetujui', 3 => 'Ditolak/Dihapus', 0 => 'Dihapus'],
            'sales_delivery_orders' => [1 => 'Menunggu', 2 => 'Terkirim', 3 => 'Ditolak/Dihapus', 0 => 'Dihapus'],
            'purchase_orders' => [1 => 'Dibuat', 2 => 'Disetujui', 0 => 'Dihapus', -1 => 'Ditolak'],
            'purchase_order_tts' => [1 => 'Menunggu', 2 => 'Disetujui', 0 => 'Dihapus', -1 => 'Ditolak'],
            'productions' => [1 => 'Menunggu', 2 => 'Berhasil', 3 => 'Ditolak', 4 => 'Menunggu Batal', 0 => 'Dihapus'],
            'production_details' => [1 => 'Menunggu', 2 => 'Berhasil', 3 => 'Ditolak', 0 => 'Dihapus'],
            'stock_opnames' => [1 => 'Menunggu', 2 => 'Disetujui', 3 => 'Ditolak', 0 => 'Dihapus'],
            'stock_opname_bahans' => [1 => 'Menunggu', 2 => 'Disetujui', 3 => 'Ditolak', 0 => 'Dihapus'],
            'product_issues' => [1 => 'Menunggu', 2 => 'Disetujui', 3 => 'Ditolak/Dihapus', 0 => 'Dihapus'],
            'return_supplies' => [1 => 'Menunggu', 2 => 'Disetujui', 3 => 'Ditolak', 0 => 'Dihapus'],
            'customer_product_returns' => [1 => 'Menunggu', 2 => 'Disetujui', 3 => 'Ditolak', 0 => 'Dihapus'],
            'customer_supply_returns' => [1 => 'Menunggu', 2 => 'Disetujui', 3 => 'Ditolak', 0 => 'Dihapus'],
            'stock_transfers' => [
                0 => 'Dihapus',
                1 => 'Pending',
                2 => 'Kirim',
                3 => 'Batal',
                4 => 'Terkirim',
                5 => 'Batal Kirim',
            ],
            'stock_transfer_details' => [1 => 'Aktif', 0 => 'Nonaktif'],
            'cashes' => [1 => 'Menunggu', 2 => 'Diterima', 3 => 'Ditolak', 0 => 'Dihapus'],
            'cash_admins' => [1 => 'Menunggu', 2 => 'Diterima', 3 => 'Ditolak', 0 => 'Dihapus'],
            'cash_gudangs' => [1 => 'Menunggu', 2 => 'Diterima', 3 => 'Ditolak', 0 => 'Dihapus'],
            'cash_armadas' => [1 => 'Menunggu', 2 => 'Diterima', 3 => 'Ditolak', 0 => 'Dihapus'],
            'cash_sales' => [1 => 'Menunggu', 2 => 'Diterima', 3 => 'Ditolak', 0 => 'Dihapus'],
            'petty_cashes' => [1 => 'Menunggu', 2 => 'Diterima', 3 => 'Ditolak', 0 => 'Dihapus'],
            'manage_stocks' => [1 => 'Menunggu', 2 => 'Disetujui', 3 => 'Ditolak', 0 => 'Dihapus'],
        ],
    ],

    /*
    | Other coded fields: "table.column" => [raw value => UI text].
    */
    'values' => [
        'purchase_orders.pembayaran' => [1 => 'Belum dibayar', 3 => 'Proses pembayaran', 2 => 'Lunas'],
        'cashes.cash_type' => [1 => 'Masuk', 2 => 'Keluar', 3 => 'Setor ke Bank'],
        'cash_admins.ca_type' => [1 => 'Manajemen Saldo Kas', 2 => 'Aktivitas Operasional'],
        'cash_admins.ca_aksi' => [0 => '-', 1 => 'Pengajuan', 2 => 'Pengembalian'],
        'cash_gudangs.cg_type' => [1 => 'Manajemen Saldo Kas', 2 => 'Aktivitas Operasional'],
        'cash_gudangs.cg_aksi' => [0 => '-', 1 => 'Pengajuan', 2 => 'Pengembalian'],
        'cash_armadas.cr_type' => [1 => 'Masuk', 2 => 'Keluar', 3 => 'Keluar 1'],
        'cash_armadas.cr_aksi' => [0 => '-', 1 => 'Pengembalian Dana Langsung', 2 => 'Aktivitas Operasional'],
        'cash_sales.cs_type' => [1 => 'Pemasukan', 2 => 'Setor ke Bank', 3 => 'Pengembalian'],
        'cash_sales.cs_aksi' => [0 => '-', 1 => 'Manajemen Saldo Kas', 2 => 'Aktivitas Operasional'],
        'cash_armada_details.crd_type' => [1 => 'Masuk', 2 => 'Keluar', 3 => 'Keluar 1'],
        'cash_sales_details.csd_type' => [1 => 'Pemasukan', 2 => 'Setor ke Bank', 3 => 'Pengembalian'],
        'log_stocks.log_type' => [1 => 'Produk', 2 => 'Bahan Mentah'],
        'log_stocks.log_category' => [1 => 'Masuk', 2 => 'Keluar'],
    ],

    /*
    | Fields kept out of tool output: line items already repeat the product
    | and unit names, so resolving the same reference again only wastes
    | tokens and makes rows harder to read.
    */
    'hide_fields' => [
        'sales_order_details' => ['product_variant_id'],
        'sales_delivery_orders_details' => ['product_variant_id'],
        'purchase_orders_details' => ['supplies_variant_id'],
        'purchase_delivery_orders_details' => ['supplies_variant_id'],
        'stock_opname_lines' => ['product_id', 'product_variant_id', 'unit_id'],
        'stock_opname_bahan_lines' => ['supplies_id', 'unit_id'],
        'return_supplies_detail' => ['pid_id'],
        'product_issues_details' => ['item_id'],
    ],

    /*
    | References whose target depends on another field in the same row.
    | Stock movements point at a product variant or a raw material,
    | depending on the kind of item being moved.
    */
    'conditional_lookups' => [
        'log_stocks.log_item_id' => [
            'on' => 'log_type',
            'map' => [
                1 => ['table' => 'product_variants', 'pk' => 'product_variant_id', 'name' => 'product_variant_name'],
                2 => ['table' => 'supplies', 'pk' => 'supplies_id', 'name' => 'supplies_name'],
            ],
        ],
    ],

    /*
    | Reference key => where to read its human name.
    | Rows come back with names instead of internal references.
    */
    'lookups' => [
        // The app shows the customer name from the notes field, so mirror that.
        'so_customer' => ['table' => 'customers', 'pk' => 'customer_id', 'name' => 'customer_notes', 'fallback' => 'customer_name'],
        'customer_id' => ['table' => 'customers', 'pk' => 'customer_id', 'name' => 'customer_notes', 'fallback' => 'customer_name'],
        'supplier_id' => ['table' => 'suppliers', 'pk' => 'supplier_id', 'name' => 'supplier_name'],
        'po_supplier' => ['table' => 'suppliers', 'pk' => 'supplier_id', 'name' => 'supplier_name'],
        'created_by' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'updated_by' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'acc_by' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'staff_id' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'person_id' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'sales_id' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'sender_id' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'receiver_id' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'qc_staff_id' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'qc_approved_by' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'ops_approved_by' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'so_cashier' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'production_created_by' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'ms_created_by' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'cancel_requested_by' => ['table' => 'staffs', 'pk' => 'staff_id', 'name' => 'staff_name'],
        'role_id' => ['table' => 'roles', 'pk' => 'role_id', 'name' => 'role_name'],
        'category_id' => ['table' => 'categories', 'pk' => 'category_id', 'name' => 'category_name'],
        'unit_id' => ['table' => 'units', 'pk' => 'unit_id', 'name' => 'unit_name'],
        'retail_unit' => ['table' => 'units', 'pk' => 'unit_id', 'name' => 'unit_name'],
        'received_unit_id' => ['table' => 'units', 'pk' => 'unit_id', 'name' => 'unit_name'],
        'safety_unit_id' => ['table' => 'units', 'pk' => 'unit_id', 'name' => 'unit_name'],
        'product_unit' => ['table' => 'units', 'pk' => 'unit_id', 'name' => 'unit_name'],
        'supplies_unit' => ['table' => 'units', 'pk' => 'unit_id', 'name' => 'unit_name'],
        'supplies_default_unit' => ['table' => 'units', 'pk' => 'unit_id', 'name' => 'unit_name'],
        'product_id' => ['table' => 'products', 'pk' => 'product_id', 'name' => 'product_name'],
        'product_variant_id' => ['table' => 'product_variants', 'pk' => 'product_variant_id', 'name' => ['product_variant_sku', 'product_variant_name']],
        'supplies_id' => ['table' => 'supplies', 'pk' => 'supplies_id', 'name' => 'supplies_name'],
        'supplies_variant_id' => ['table' => 'supplies_variants', 'pk' => 'supplies_variant_id', 'name' => 'supplies_variant_name'],
        'variant_id' => ['table' => 'variants', 'pk' => 'variant_id', 'name' => 'variant_name'],
        'warehouse_id' => ['table' => 'warehouses', 'pk' => 'id', 'name' => 'warehouse_name'],
        'retail_warehouse_id' => ['table' => 'warehouses', 'pk' => 'id', 'name' => 'warehouse_name'],
        'from_warehouse_id' => ['table' => 'warehouses', 'pk' => 'id', 'name' => 'warehouse_name'],
        'to_warehouse_id' => ['table' => 'warehouses', 'pk' => 'id', 'name' => 'warehouse_name'],
        'destination_warehouse_id' => ['table' => 'warehouses', 'pk' => 'id', 'name' => 'warehouse_name'],
        'last_active_warehouse_id' => ['table' => 'warehouses', 'pk' => 'id', 'name' => 'warehouse_name'],
        'warehouse_type_id' => ['table' => 'warehouse_types', 'pk' => 'id', 'name' => 'warehouse_type_name'],
        'bank_id' => ['table' => 'banks', 'pk' => 'bank_id', 'name' => 'bank_kode'],
        'cc_id' => ['table' => 'cash_categories', 'pk' => 'cc_id', 'name' => 'cc_name'],
        'area_id' => ['table' => 'areas', 'pk' => 'area_id', 'name' => 'area_name'],
    ],
];
